version: "3"

services:
  application:
    build:
      context: ./
      dockerfile: docker/application/Dockerfile
    container_name: application
    environment:
      JAVA_OPTS: -Dspring.profiles.active=dev
    links:
      - postgres
      - postgres-test
    volumes:
    - ./api/build/libs/rest-api-advanced.jar:/app/rest-api-advanced.jar
    ports:
      - 8080:8080

  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=rest
      - POSTGRES_USER=rest
      - POSTGRES_DB=rest
      - PGDATA=/pg-data
    ports:
      - 54321:5432
    volumes:
      - pg-data:/pg-data

  postgres-test:
    container_name: postgres-test
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=rest-test
      - POSTGRES_USER=rest-test
      - POSTGRES_DB=rest-test
      - PGDATA=/pg-data-test
    ports:
      - 54322:5432
    volumes:
      - pg-data-test:/pg-data-test

volumes:
  pg-data:
  pg-data-test: