version: "3"

services:
  tomcat:
    build:
      context: ./
      dockerfile: ./docker/tomcat/Dockerfile
    container_name: tomcat
    links:
      - postgres
    volumes:
    - ./docker/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./docker/tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
    - ./build/libs/rest-api-basics.war:/usr/local/tomcat/webapps/rest-api-basics.war
    ports:
      - 8082:8080

  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=rest
      - POSTGRES_USER=rest
      - POSTGRES_DB=rest
      - PGDATA=/pg-data
    ports:
      - 54321:5432
    volumes:
      - pg-data:/pg-data

volumes:
  pg-data: